### ISSUE TITLE
Erro when render template in quarto

### ISSUE THREAD

**Issue by ambarja** [spcanelon/silvia#105]
Hello, recently I have been using the Quarto website template, but I encountered some errors. Here are the details: I couldn't find the following files.

 ```yaml
      light:
        - cosmo
        - assets/silvia-theme-light.scss
        - assets/silvia/colors-light.scss
        - assets/silvia/fonts.scss
      dark: 
        - cosmo
        - assets/silvia-theme-dark.scss
        - assets/silvia/colors-dark.scss
    highlight-style:
      light: assets/silvia/a11y-light.theme
      dark: assets/silvia/a11y-dark.theme
```
![image](https://github.com/spcanelon/silvia/assets/23284899/9aaa2f5d-c0a8-4f33-afe1-3f537d4af4de)
